name: datetime_picker_formfield
description: A widget that wraps a TextFormField and integrates the date and/or time picker dialogs.
version: 0.2.0
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/datetime_picker_formfield

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.0.0 <2.0.0"